version: '3.7'

services:
  web:
    image: "btre"
    container_name: "dev"
    build: btre_project
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 "
    volumes:
      - ./btre_project/:/app/
    ports:
      - 8000:8000
    env_file:
      - btre_project/.env.dev
  postgres:
    image: postgres:12.0-alpine
    container_name: "postgres_test"
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
       - btre_project/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: